import { Heebo, Bona_Nova } from "next/font/google";
import "./globals.scss";

const heebo = Heebo(
  {
    subsets: ["hebrew", "latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    variable: '--font-heebo'
  }
);
const bonaNova = Bona_Nova(
  {
    subsets: ["hebrew", "latin"],
    weight: ["400", "700"],
    variable: '--font-bona'
  });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="he">
      <body className={`${heebo.variable } ${bonaNova.variable}`}>{children}</body>
    </html>
  );
}
